### PR TITLE
Update user.js

### PR DESCRIPTION
**Pull request by azriakmalk**
# HacktoberFest 2020🎓

This pull request template helps you complete an pull request to the **HacktoberFest 2020**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by adding a profile picture on the `img` folder and followed the naming convention mentioned in the instructions (`username.png/jpg/jpeg/gif`).
- [x] I have used this `["Your Name", "Image URL(./img/username.png)", "Bio", "Your Github Link"]` template to add my information in user.js.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I understand the photo added to the template will be used in the Website.

### CODE REVIEW

**Review by vimalverma558 — CHANGES_REQUESTED** [review]
Follow Readme.md

**Comment by azriakmalk** [comment]
I've been followed Readme.md

**Comment by vimalverma558** [comment]
Everything is ok, but changed user.js file structure,
Please organise previously 👍

**Comment by azriakmalk** [comment]
oke done, can u check my pr again? thanks

**Review by vimalverma558 — APPROVED** [review]

**Pull request merged**
